nome = (input ("Informe seu nome: "))
nota1 =  float (input("Informe a nota 1: "))
nota2 =  float (input("Informe a nota 2: "))
media = float ((nota1 + nota2)/2)
print (f"{nome} sua média é: {media}")